language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.1

install:
    - composer install --no-interaction --prefer-source

script:
    - php vendor/bin/phpstan analyse ./src ./tests --level 5
    - php vendor/bin/phpcs --standard=PSR2 ./src ./tests
    - php vendor/bin/phpunit
